changelog:
  sections:
    - title: "🚀 Features"
      labels: ["feature", "enhancement", "new"]
    - title: "🐛 Bug Fixes"
      labels: ["bug", "fix"]
    - title: "🧰 Maintenance"
      labels: ["chore", "refactor", "docs", "test"]
    - title: "📦 Dependencies"
      labels: ["dependencies"]
  contributors:
    title: "Contributors"
