name: Release Notes Generator

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to get all tags and history

      - name: Get Latest and Previous Tags
        id: tags
        run: |
          CURRENT_TAG=$(git describe --tags --abbrev=0)
          PREV_TAG=$(git describe --tags --abbrev=0 "$CURRENT_TAG^" 2>/dev/null || echo "")

          echo "Current tag: $CURRENT_TAG"
          echo "Previous tag: $PREV_TAG"

          echo "current_tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Generate Commit List
        id: changelog
        run: |
          if [ -z "${{ steps.tags.outputs.prev_tag }}" ]; then
            git log --pretty=format:"- %s (%h)" > commits.txt
          else
            git log ${{ steps.tags.outputs.prev_tag }}..${{ steps.tags.outputs.current_tag }} --pretty=format:"- %s (%h)" > commits.txt
          fi

          echo "Commits:"
          cat commits.txt

          {
            echo "commits<<EOF"
            cat commits.txt
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tags.outputs.current_tag }}
          name: Release ${{ steps.tags.outputs.current_tag }}
          body: ${{ steps.changelog.outputs.commits }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
